name: Build

env:
  MOD_NAME: AsphaltRoadsPatched

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          sparse-checkout: |
            thumbnail.png 
            info.json 
            LICENSE.md
            license.md
            LICENSE
            license
            changelog.txt 
            locale 
            util
            prototypes
            migrations
            graphics
            data.lua
            control.lua
            config.lua
            control.lua
            data-updates.lua
            data.lua
            readme.md
            settings.lua
            tile_reconverter_config.lua
            tile_reconverter.lua
            data-final-fixes.lua
          sparse-checkout-cone-mode: false

      - name: Get version number
        run: |
          REGEX="(?<=Version: )([1-9]\.[0-9]\.[0-9])" 
          echo LATEST=$(grep -m 1 -oP "$REGEX" changelog.txt) >> $GITHUB_ENV

      - name: Make mod folder
        run: | 
          mkdir ./${{env.MOD_NAME}}
          mv $(ls --ignore=${{env.MOD_NAME}}) ./${{env.MOD_NAME}}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: "${{env.MOD_NAME}}_${{env.LATEST}}"
          path: |
            ${{github.workspace}}/*
            !.git*
          retention-days: 5

